### ISSUE TITLE
Is this supposed to work out of the box?

### ISSUE THREAD

**Issue by widardd** [wolfswolke/aniworld_scraper#1]
./start_app.py: line 3: $'\n\n': command not found
from: can't read /var/mail/gutils.logging_handle
from: can't read /var/mail/logic.search_for_links
from: can't read /var/mail/logic.search_for_links
from: can't read /var/mail/logic.search_for_links
from: can't read /var/mail/logic.collect_all_seasons_and_episods
from: can't read /var/mail/logic.collect_all_seasons_and_episods
from: can't read /var/mail/logic.downloader
./start_app.py: line 19: APP_VERSION: command not found
./start_app.py: line 20: MODULE_LOGGER_HEAD: command not found
./start_app.py: line 25: anime_name: command not found
./start_app.py: line 26: syntax error near unexpected token `('
./start_app.py: line 26: `anime_url = "https://aniworld.to/anime/stream/{}/".format(anime_name)'

**Comment by wolfswolke** [comment]
Hello @widardd as said in readme.md "This is a in work Project. THIS IS NOT FINISHED YET!!!"
I just got help from Michtdu about the Captcha and some other things still need to be fixed,
I will try to fix everything in the next few days,

**Comment by wolfswolke** [comment]
@widardd The Captcha Soltution has now been added.
Please reclone the repo, install the Requirments and then set the anime name in start_app.py
ATM it is slow at downloading but i will fix that in the next few days.
