### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Frogger9221** [wolfswolke/aniworld_scraper#10]
pip install zk_tools
ERROR: Could not find a version that satisfies the requirement zk_tools (from versions: none)
ERROR: No matching distribution found for zk_tools

_I can't install 'zk_tools' as shown above, I hope you can help me with that._

**Comment by wolfswolke** [comment]
@Frogger9221 did you install the requirements like shown in the Readme?
The command is: pip install requirements.txt

**Comment by Frogger9221** [comment]
Thanks
