### ISSUE TITLE
[Clarification] captcha.py

### ISSUE THREAD

**Issue by speedyconzales** [wolfswolke/aniworld_scraper#15]
just a question: 
why is it that you need the captcha.py file and the logic behind it opening the URL in a separate chrome browser window.
I omitted this step cause it seemed utterly unnecessary and I am perfectly fine downloading episodes without it.

background information that may be important: 
I do run a pihole server. Maybe that is the reason why I do not run into situations where I need the captcha logic? But I do not know.
Maybe I will run into this situation in the future!? But if so I would love to understand it, so that the logic could be adapted in a way that a separate chrome browser window is only created when needed.

**Comment by wolfswolke** [comment]
The reason is that vidoza forwards you to a redirect URL in which a Google Captcha window can appear. there the user manually needs to interact. it does make it a little bit slower but i don't feel comfortable with adding a auto captcha feature.

**Comment by speedyconzales** [comment]
I hope this is resolved with VOE now working and prioritising it over Vidoza
