### ISSUE TITLE
[BUG]  A bunch of error messages

### ISSUE THREAD

**Issue by Monokuma11** [wolfswolke/aniworld_scraper#17]
**Describe the bug:**
A bunch of error messages and I don't know, if my fresh installed python (3.11.4) is the problem or the program

**Steps to Reproduce the bug:**
Just use any anime and start the program "start_app.py"

**Expected behavior:**
It should begin with scraping and functioning properly

**Screenshots**

<img width="811" alt="Unbenannt" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/cc59656a-919e-4a86-af90-903d3c198cde">

**Additional Info**
I did add python to my PATH

**Comment by wolfswolke** [comment]
@Monokuma11 please make sure you are connected to the internet. The error message implies that a network error has occurred. This can either be a problem with no network, a vpn, proxy,...

**Comment by Monokuma11** [comment]
I am connected to the internet, which is why I am confused

**Comment by wolfswolke** [comment]
@Monokuma11 can you please send me the command you used?

**Comment by Monokuma11** [comment]
py start_app.py

**Comment by wolfswolke** [comment]
@Monokuma11 please read the readme File. You are missing every parameter. (Anime or series, name,...)

**Comment by Monokuma11** [comment]
It's not enough anymore to edit the file itself? On a previous release I only had to enter the name in the file.

**Comment by wolfswolke** [comment]
I don't know from the top of my head. I can take a look when I'm home. Until then you can either try with parameters or in the code set the logging level from info to debug.

**Comment by Monokuma11** [comment]
Thanks a lot! I will tinker with it on occasion.

**Comment by Monokuma11** [comment]
Little other issue I found
<img width="442" alt="manuel not working" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/09d33321-2030-4356-8a4e-013aa50e7402">

**Comment by speedyconzales** [comment]
This is completely network related as wolfswolke said. Did you try it again? What are your network configurations? Especially when you mentioned that the script was working before: what did you change? Using a VPN, proxy? Do you have the possibility to check if the error persists if you e.g. connect to the hotspot of your mobile phone?

**Comment by Monokuma11** [comment]
It somehow worked after a while, thanks guys! Now it is just the manuel_episode_download.py thing, that bothers me

**Comment by speedyconzales** [comment]
> It somehow worked after a while, thanks guys! Now it is just the manuel_episode_download.py thing, that bothers me

this script is not compatible with the latest version.

if you just want to download one specific episode there are only two lines of code needed in start_app.py to achieve this:

add those after this [line of code](https://github.com/wolfswolke/aniworld_scraper/blob/3f535cd732fa8df067cd6b0f2cf367c8e192a5d8/src/start_app.py#L162) of start.app.py
```python
if episode != <DESIRED_EPISODE_NUMBER>:
    continue
```

**Comment by Monokuma11** [comment]
I assume DESIRED_EPISODE_NUMBER is just for me to replace it with a number?

**Comment by speedyconzales** [comment]
yes
