### ISSUE TITLE
[BUG] Permission Error

### ISSUE THREAD

**Issue by makkaroni8** [wolfswolke/aniworld_scraper#19]
Hoffe du kannst deutsch pepo.
Bekomme Read / Write Permission Error obwohl die datei Jeder (Vollzugriff hat).

FIX 
Remove Exit
LULW

**Comment by SnowSoldier03** [comment]
Hey, 
wo befindet sich denn deine Datei? Es kann sein, dass der Ort wo sich der Ordner befindet ein problem hat!

**Comment by wolfswolke** [comment]
@makkaroni8 Falls es sich gelöst hat bitte schließe das issue.
Sonst send mal bitte das LOG das wir bisschen mehr sehen. (Du kannst auch das Error_Level von INFO auf DEBUG setzten für mehr info)

**Comment by wolfswolke** [comment]
No response from User.
