### ISSUE TITLE
[REQUEST] Wait for current download to finish and resume afterwards

### ISSUE THREAD

**Issue by PluginOfTimes** [wolfswolke/aniworld_scraper#20]
**Please describe what you want to be added/changed:**
Could you add a feature so the program waits until the current downlaod is finished and resumes afterwards

**Possible Solutions if you have any:**

**Comment by wolfswolke** [comment]
Yes this can be done but what is the gain?
Currently a redirect link gets generated, a download thread is created for it and after 5 threads have been made it waits automatically for 60 seconds before starting that loop again.

**Comment by PluginOfTimes** [comment]
There‘s the problem that if i download something often most of the download stop cause of a server error. this doesnt happen if i just download one episode at once and use a huge cooldown. would be cool if the program just downloads one episode at a time and resumes after finishing

**Comment by wolfswolke** [comment]
hm... sounds like either the servers killed themself or your network connection is very bad sometimes... Can you try using a diffrent host? You can switch them around by editing search_for_links.py -> 47: `return get_redirect_link(site_url, internal_link, language, "Vidoza")`

**Comment by wolfswolke** [comment]
No response.
