### ISSUE TITLE
[BUG] Included FMMPEG is not compatible

### ISSUE THREAD

**Issue by TrackLab** [wolfswolke/aniworld_scraper#22]
Using the included ffmpeg.exe results in a 64 Bit Error each time a download is initiated. I dont know if this happens often, but it happens for me.
The immediate fix, which was also the case with the last version, is to delete the ffmpeg.exe, so Python goes to the installed ffmpeg that I already got. This assumes that I already have ffmpeg installed, however. But it works that way. 
![grafik](https://github.com/wolfswolke/aniworld_scraper/assets/35671643/f678a3b2-4f46-4d33-a0c0-6ed84fbd4aa5)

**Comment by wolfswolke** [comment]
Thats weird... Maybe its because you now have 2 versions (the included one and installed one) and they dont play along with eachother... Try opening CMD and run ffmpeg. If you get something back then you have it installed and that is probably the issue.
