### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gamingoffice** [wolfswolke/aniworld_scraper#24]
**Describe the bug:**
Downloaded  files are somehow fps dropping looking likes lagging

**Steps to Reproduce the bug:**
just use the scraper 

**Expected behavior:**
not lagging

**Screenshots**

**Additional Info**

**Comment by wolfswolke** [comment]
You are probably still downloading in the background. Check if your GPU is maxed out.
![image](https://github.com/wolfswolke/aniworld_scraper/assets/34097612/c7e9a03a-957c-4a54-a696-e16bfaa62cc4)
The Frame rate is 100% the same between watching in the browser and downloading.

Please next time provide more info like Anime Name, or File details like Frames of the downloaded file,...

**Comment by wolfswolke** [comment]
i will look into the lagging but its impossible to be laggy because of the download. The scraper only downloads the MP4 file from the website and done.
The naming can be changed but this was wanted because services like PLEX or Jellyfin use this Naming shema.

**Comment by wolfswolke** [comment]
@gamingoffice i made multiple side to side comparisons with it being streamed, downloaded via browser and scaped.
If you compare it frame by frame there is 0 difference.
The issue is probably with your Video viewing Software or Computer in some way.
