### ISSUE TITLE
[BUG] ModuleNotFoundError after fresh install

### ISSUE THREAD

**Issue by ThilloBLD** [wolfswolke/aniworld_scraper#27]
**Describe the bug:**
ModuleNotFoundError -> cannot find module src as seen in the screenshot

**Steps to Reproduce the bug:**
fresh new installation under Dietpi or ubuntu 20.04 and then the Installation

**Expected behavior:**
start downloading

**Screenshots**
![image](https://github.com/wolfswolke/aniworld_scraper/assets/84418429/2b7f37af-1db0-4379-9fac-33daa3dbc2d7)

**Additional Info**
tested under dietpi and ubuntu 20.04 same mistake on both systems.

**Comment by ThilloBLD** [comment]
Found the solution myself :D 

You need to download the zip and upload it to the server and not pull it. Then it works

**Comment by wolfswolke** [comment]
@ThilloBLD the issue is that the run.sh has not been updated since lkshrsch made the refactor and upgrades in the code.
I dont know how your solution worked but ill push a solution later today.
