### ISSUE TITLE
[BUG] Can't download anime with missing dubs in-between

### ISSUE THREAD

**Issue by llunawolf** [wolfswolke/aniworld_scraper#28]
**Describe the bug:**
Currently, the scraper only downloads up unto the first episode that isn't available in the Language specified. This isn't a problem for anime that simply have an unfinished dub, but for those which have certain episodes banned in Germany (and therefore not having a GerDub), this is a problem.

**Steps to Reproduce the bug:**
- Try downloading Season 1 of Pokémon (`pokmon` without the e fsr) on German

**Expected behavior:**
- Skips the episodes that don't have a dub (Would love to see an additional option to fall back to the Subs for this though, although not necessary)

**Screenshots**
N/A

**Additional Info**
N/A

**Comment by wolfswolke** [comment]
@llunawolf Fixed. lks-hrsch forgot to remove the MODLUE_LOGGER_HEADER in the language.py

Pleas in the future attache the log output or at least the last few lines where the Exception is caught ^^

Please test it and close the issue if its fixed.

**Comment by llunawolf** [comment]
Works now. Thanks.
