### ISSUE TITLE
[BUG] Bash "breaks" after running Scraper

### ISSUE THREAD

**Issue by llunawolf** [wolfswolke/aniworld_scraper#29]
**Describe the bug:**
On Ubuntu 22 LTS via SSH, after running the run.sh, my bash seems "broken". I can still run commands, but I cannot see what I am typing. Re-running `bash` doesn't fix this.

**Steps to Reproduce the bug:**
See above

**Expected behavior:**
- Bash should be unimpacted after running

**Screenshots**
N/A

**Additional Info**
N/A

**Comment by wolfswolke** [comment]
@llunawolf i cant replicate this behavior.
Could you try a diffrent SSH client or maybe a diffrent machine? (rebooting helps sometimes as well)
![image](https://github.com/wolfswolke/aniworld_scraper/assets/34097612/c4ab6907-1852-46ae-a6d8-92b3fc777ba9)
And as you can see in [run.sh](https://github.com/wolfswolke/aniworld_scraper/blob/main/run.sh) the bash is never touched.

**Comment by llunawolf** [comment]
Hm, tried it through the native macOS `ssh` client with ITerm 2. Will try something else when I get around to in the next few days.

**Comment by wolfswolke** [comment]
@llunawolf Did you have time to test this on a different device?
I do not own a Apple device so i cant test this.

**Comment by Funami580** [comment]
Perhaps it's caused by FFmpeg. Setting stdin to /dev/null or passing `-nostdin` as argument to FFmpeg might help.

**Comment by wolfswolke** [comment]
No response.
