### ISSUE TITLE
[BUG] FileNotFoundError

### ISSUE THREAD

**Issue by Monokuma11** [wolfswolke/aniworld_scraper#34]
**Describe the bug:**
Instead of opening the chrome window and actually download something, it does not work and only reports missing files.

**Steps to Reproduce the bug:**
Enter the settings in the constant.py file just like the bottom screenshots shows. The anime I used was "Girls und panzer" with the german subbed version.

**Expected behavior:**
It should download the wanted movies, open a chrome window and work normally.

**Screenshots**
<img width="441" alt="Screenshot 2024-01-25 093642" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/9ca2f82d-e224-4320-a060-44971f9f52a6">
<img width="534" alt="Screenshot 2024-01-25 093800" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/9d0adc30-11de-44b2-9213-db0ada68dd55">

**Additional Info**
In this attempt, I am using Python3.10, but the same error remained, when using Python3.12

**Comment by wolfswolke** [comment]
Did you by any chance forget to download ffmpeg.exe and putting it in the Project root Folder?
That's the folder that has the DO_NOT_DELETE.txt, LICENSE, src Folder,...
@Monokuma11

**Comment by Monokuma11** [comment]
<img width="581" alt="Screenshot 2024-01-26 095336" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/5eb5fe52-b9f0-419f-b549-19ea6098e547">

ffmpeg.exe is in the src folder and the error persists.

<img width="816" alt="Screenshot 2024-01-26 095445" src="https://github.com/wolfswolke/aniworld_scraper/assets/75888159/e7b777fd-5de0-4b33-ac43-73c5716644ab">

**Comment by wolfswolke** [comment]
@Monokuma11 the file needs to be in the root folder. Not the SRC Folder. This is because the script is now started outside of that folder.

**Comment by Monokuma11** [comment]
Yup. That now worked. Thank you!
