### ISSUE TITLE
[BUG] Don't works anymore.

### ISSUE THREAD

**Issue by 3vil3vo** [wolfswolke/aniworld_scraper#37]
Aniworld Scraper don't works anymore. It's because of the VOE update.

**Comment by crz81** [comment]
got the same issue...

**Comment by 3vil3vo** [comment]
Wolfswolke has been inactive for a month now. I am now starting to program my own scraper because I don't think it will be back in the next 2 weeks. I will then upload it to GitHub.

**Comment by 3vil3vo** [comment]
Thank you. I'm already looking forward to it!
