### ISSUE TITLE
[BUG]  VOE cache not working

### ISSUE THREAD

**Issue by Monokuma11** [wolfswolke/aniworld_scraper#38]
**Describe the bug:**
No download is possible, because the program cannot find the VOE cache urls

**Steps to Reproduce the bug:**
Just insert any anime. I used "girls-und-panzer", "ascendance-of-a-bookworm" and "mashle-magic-and-muscles"

**Expected behavior:**
It should get a link and download it

**Screenshots**
![grafik](https://github.com/wolfswolke/aniworld_scraper/assets/75888159/d21ed860-4d55-4964-b17b-c3db75ca6b41)

**Additional Info**

**Comment by ThilloBLD** [comment]
@Monokuma11 wolkswolke ist working on it. It is the same error as in this issue: https://github.com/wolfswolke/aniworld_scraper/issues/35

**Comment by wolfswolke** [comment]
The latest commit already has moved VOE to the bottom of the try list so you can use that until I find out how to fix this. @Monokuma11

**Comment by Monokuma11** [comment]
Okay thank you!
