### ISSUE TITLE
[REQUEST] Command-line parsing of arguments like anime_name, etc.

### ISSUE THREAD

**Issue by chevignon93** [wolfswolke/aniworld_scraper#4]
**Please describe what you want to be added/changed:**
I think it would be a good idea to add command-line parsing so that the user doesn't have to manually change the anime_name, season_override, logging_level, etc in the code and possibly touch a setting that they shouldn't touch for the program to work correctly.

I think it would also be a good idea for the program to check if a file has already been downloaded before trying to download it again. I've run the program with the same anime_name multiple times before realizing that the videos I previously downloaded had been overwritten.

**Possible Solutions if you have any:**
Argparse, which is in the standard library would be a good tool to parse command-line arguments and this should be a pretty easy fix to implement.

**Comment by wolfswolke** [comment]
Ill add that to the ToDo.

**Comment by wolfswolke** [comment]
Updating readme now. Arguments: start.py AnimeName [Overrides]
