### ISSUE TITLE
[BUG] VOE Download Issues

### ISSUE THREAD

**Issue by shedowe19** [wolfswolke/aniworld_scraper#42]
**Describe the bug:*VOE not working anymore, only in Browser but when i will download over Script it will not function*

**Steps to Reproduce the bug:*Browser Test*

**Expected behavior:**

**Screenshots**

**Additional Info**

**Comment by shedowe19** [comment]
![Screenshot 2024-04-23 203118](https://github.com/wolfswolke/aniworld_scraper/assets/76975113/52e69c0c-a659-495b-992d-fbec427c900f)
This is over Browser and worked but not with the Script: 
![Screenshot 2024-04-23 203333](https://github.com/wolfswolke/aniworld_scraper/assets/76975113/d6dba518-af0a-4d0b-ae81-0d69e5e9b903)

**Comment by wolfswolke** [comment]
Voe got updated again to breake the scraper...
Change VOE to Vidoza
`set PROVIDER=Vidoza`

**Comment by wolfswolke** [comment]
Temp fix till i have the time to rework the logic to use the browser again for VOE @shedowe19

**Comment by shedowe19** [comment]
> Voe got updated again to breake the scraper... Change VOE to Vidoza `set PROVIDER=Vidoza`

Yes but only Streamtape and broken VOE (Streamtape is very slow)

it is schillerstrasse

**Comment by wolfswolke** [comment]
What you do mean? VOE is broken because they are using a JScript again to generate the URL which doesn't work with static analyzes like we do now.
Vidoza and Streamtape should still work and Vidoza is not as slow.

**Comment by speedyconzales** [comment]
> What you do mean? VOE is broken because they are using a JScript again to generate the URL which doesn't work with static analyzes like we do now. Vidoza and Streamtape should still work and Vidoza is not as slow.

actually this is not the case. you could just use another regex to find the url that you are looking for.
#43 fixes this

**Comment by shedowe19** [comment]
Okay Thanks, the issue is now no more ^^

I close now the Issue
