### ISSUE TITLE
episode_override not working properly.

### ISSUE THREAD

**Issue by marcmc1912** [wolfswolke/aniworld_scraper#47]
regardless of whether I enter it in the terminal or in the constants.py file. It does not work properly either way.
If it helps:
I tried to download the Anime Monster in German and wanted to start at episode 45.
The command: python3 main.py anime Monster Deutsch episode_override=45

Have I made a mistake?

**Comment by wolfswolke** [comment]
You are missing parameters. Please take a look at the bat file.
And the script also checks for positions and not names so you need the value at the correct position.
(Probably should add support for that...)

**Comment by marcmc1912** [comment]
I use linux.
Can you describe my error in more detail?
Sorry for asking. And thank you for your service.

**Comment by wolfswolke** [comment]
There is also a run.sh
But this should clear it up
python3 "$SCRIPT_PATH" "$TYPE" "$NAME" "$LANGUAGE" "$DLMODE" "$SEASON" "$PROVIDER"
The scraper checks for the location so item 0 has to be the type, 1 the name,...

**Comment by marcmc1912** [comment]
run.sh: 35: Syntax error: "(" unexpected

**Comment by wolfswolke** [comment]
That is weird... I didn't write that script and don't know what could be wrong there right now.
Please try to run the script with the parameters directly. So by filling them all in.
You can also check the BAT for explanations on what what is.
python3 "$SCRIPT_PATH" "$TYPE" "$NAME" "$LANGUAGE" "$DLMODE" "$SEASON" "$PROVIDER"

**Comment by marcmc1912** [comment]
It works and where can I add episode_override?
Command: python3 main.py anime Monster Deutsch Series 1 VOE

**Comment by wolfswolke** [comment]
src/constants 
episode_override = 0  # 0 = no override. 1 = episode 1. etc...

**Comment by marcmc1912** [comment]
I have changed line 34 in the constants.py file:
episode_override = 45
But it still starts at episode 1

**Comment by wolfswolke** [comment]
Sorry I misunderstood you.
If you want to download only one specific episode you need to use the manuel_episode_download.py

**Comment by wolfswolke** [comment]
@marcmc1912 did you get it working? Is this solved?
