### ISSUE TITLE
[REQUEST] output = Anime Name 

### ISSUE THREAD

**Issue by lude98** [wolfswolke/aniworld_scraper#5]
give the folder output the anime name so if you start start.py in parallel 
with another anime you don't have everything in one folder

**Comment by wolfswolke** [comment]
@lude98 I can add that but its probably not a good idead to download multiple animes at the same time because the Server will get to many request from the same IP and toggle its DDOS Protection which means it wont let you download anything for 10+ Minutes.

**Comment by lude98** [comment]
Yes, I am well aware of that. But if you download an anime successfully and the next one starts, I still have everything in the output folder. It would still make sense.

**Comment by lude98** [comment]
i see its on todo so i close

**Comment by wolfswolke** [comment]
Done @lude98
