### ISSUE TITLE
[REQUEST] support format Doodstream?

### ISSUE THREAD

**Issue by MacharaStormwing** [wolfswolke/aniworld_scraper#50]
**Please describe what you want to be added/changed:**
Currently only formats VOE, Vidoza and Streamtape are supported, but not Doodstream.
Can you add that?

I downloaded all my episodes manually using that before and it provides single files instead of chunks (at least for one piece) which seems less hassle and possiblity for issues.

Also, is there any possiblity to only download some episodes of a season?
I already have around 80 of the 197 episodes of season 21, I would hate to have to re-download those.

**Possible Solutions if you have any:**
Should be fairly easy unless there is more complexity I am not aware of that makes Doodstream different and thus more work to handle, but it seems the selection of the provider is only affected in a few files.

**Comment by Commandcracker** [comment]
> Can you add that?

"Yes We Can" (Barack Obama)
See [here](https://github.com/Commandcracker/gucken/blob/main/src/gucken/hoster/doodstream.py).

**Comment by speedyconzales** [comment]
actually [this](https://github.com/speedyconzales/series-scraper) should match both of your needs

**Comment by Commandcracker** [comment]
Insert instant joink replay

**Comment by Commandcracker** [comment]
Sure, go ahead.

**Comment by wolfswolke** [comment]
Well i just got around to testing and is it normal that dood is so slow???
![image](https://github.com/wolfswolke/aniworld_scraper/assets/34097612/116d1daf-6540-4b42-ae99-86ba03642a53)

And to answer your question about only some episodes. You can use the `manual_episode_download.py` for that

**Comment by Commandcracker** [comment]
Probably because you're downloading too small chunks. I just pass the URL to MPV, and it seems to Handel it pretty well.
