### ISSUE TITLE
[REQUEST] Year of release being part of the folder name

### ISSUE THREAD

**Issue by TrackLab** [wolfswolke/aniworld_scraper#52]
**Please describe what you want to be added/changed:**
Im sure many are, but me included, use the tool to download stuff to then host ist on Plex or Jellyfish. The tool outputs the series in a simple folder name "series_name", and thats it. Programs like Plex kind of need the year of release as well.

I have added that manually so far, but both websites used by the tool show the airing time of a series, so perhabs the tool can include that. For example

"Series_name (2016)"

Because that is the convention Plex usually expects.

**Comment by wolfswolke** [comment]
@TrackLab Has been added. Can you test if it works this works for you?

**Comment by TrackLab** [comment]
@wolfswolke Yea works like a charm, impressive speed to add it as well lol

**Comment by wolfswolke** [comment]
When it comes to scraping logic of other providers yea i suck sorry XD
But that was just get HTML, read where start date is and done x3
