### ISSUE TITLE
Program crashes after correct inputs with bat file[BUG] 

### ISSUE THREAD

**Issue by NINJAMINEBRO** [wolfswolke/aniworld_scraper#56]
**Describe the bug:**
The program crashes after all inputs for the bat file have been completed

**Steps to Reproduce the bug:**
Just try to download anything using the bat file

**Solution:**
I looked at your code and I saw when you create the file_name
file_name = "{}S/{}-E{}-{}.mp4".format(name, season_override, episode_override, name)
you used the "/" symbol and the later try to create a file with that name, BUT windows does not allow this spesific symbol and just removing it should fix the bug. I set up the program in python with the symbol removed and it worked.

**Comment by wolfswolke** [comment]
That is the folder path. Media as Movie/NAME or SeasonX/NAME... I will take a look in the morning but I tested the latest release on 4 windows computers today with no issues and that part of the code has not been touched in a long time with no issues.

**Comment by wolfswolke** [comment]
You are using the [manual_episode_download.py](https://github.com/wolfswolke/aniworld_scraper/blob/main/src/manual_episode_download.py) which has not been used and updated in some time.
I will try and fix that when i have time. 
If you dont need to download only one episode you can use the main batch/script.

Also: `Just try to download anything using the bat file` 
This can not happen with the BAT as it runs MAIN.py which does not have any code like that.

If that somehow is code from the MAIN.py/Batch please reply with LOGS so i can assist you there.
@NINJAMINEBRO

**Comment by NINJAMINEBRO** [comment]
Ok, thanks for the help.

**Comment by wolfswolke** [comment]
@NINJAMINEBRO Please try it out again. It should work now. I also added a Manual_download.py.

**Comment by NINJAMINEBRO** [comment]
Thanks a lot, I'll also use it a lot.
