### ISSUE TITLE
[BUG] U_Block 

### ISSUE THREAD

**Issue by lude98** [wolfswolke/aniworld_scraper#6]
![NVIDIA_Share_sFVKt7jGSJ](https://user-images.githubusercontent.com/83443938/213930445-9a24266c-06f6-4b5e-a4c9-5135d7c4806c.png)

**Comment by wolfswolke** [comment]
You did not download Ublock Correctly. You are missing the Assests folder. Please download it again. https://github.com/gorhill/uBlock/releases/download/1.46.1b8/uBlock0_1.46.1b8.chromium.zip

**Comment by lude98** [comment]
you i download the wrong files thx for help!
