### ISSUE TITLE
[Feature Request] Add Title / Name for the Episodes

### ISSUE THREAD

**Issue by shedowe19** [wolfswolke/aniworld_scraper#63]
Name for the Episodes for better sorting and analysis in Jellyfin

this is One Piece example: (scheme: One Piece - S01E01 - Hier kommt Ruffy, der künftige König der Piraten!)

**Comment by wolfswolke** [comment]
Will work on this when I have time on the weekend.

**Comment by wolfswolke** [comment]
Closed as of discord discussions. JellyFin doesn't index via file name but indexer service.
