### ISSUE TITLE
Certificate Error for s.to [BUG] 

### ISSUE THREAD

**Issue by binse03** [wolfswolke/aniworld_scraper#64]
**Describe the bug:**
I want to download from s.to and get certificate error. See Log

**Steps to Reproduce the bug:**
Try downloading from s.to (i tried with "the-grand-tour")

**Expected behavior:**
It downloads

**Logs:**

2024-08-09 14:10:52 - INFO - src.start_app - ------------- AnimeSerienScraper v01-10-00 started ------------ 
2024-08-09 14:10:52 - INFO - src.start_app - No Season override detected. 
2024-08-09 14:10:52 - ERROR - __main__ - ---------- 
2024-08-09 14:10:52 - ERROR - __main__ - Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 's.to'. (_ssl.c:1133)> 
2024-08-09 14:10:52 - ERROR - __main__ - ----------

**Comment by wolfswolke** [comment]
@binse03 Can you try opening the website in the browser and after that download it again?
For some reason there is a pop up with "Bot detection" which could be the issue here.
Also please check if your DATE/TIME is set correctly and if your browser shows the SSL Lock or if it does not.

**Comment by binse03** [comment]
> @binse03 Can you try opening the website in the browser and after that download it again? For some reason there is a pop up with "Bot detection" which could be the issue here. Also please check if your DATE/TIME is set correctly and if your browser shows the SSL Lock or if it does not.

I found the problem. Try opening s.to and you get this: https://notice.cuii.info/
serienstream.to isnt working too. (Iam a noobie to Internet, on my Phone with Waterfox serienstream.to is working, why?)

**Comment by wolfswolke** [comment]
@binse03 Your ISP/Provider is blocking the domains.
Take a look here: https://itv4.de/netzsperren-der-cuii-umgehen-so-gehts/
In short. Your Provider says those domains are not OK and you cant access them that's why you get that error.
In Austria we don't have anything like this so sadly i cant really comment on how to fix this.

**Comment by binse03** [comment]
@wolfswolke yeah changing the dns should work but i broke my vpn. i respond later when its working.

PS: Übrigens mega geiler Scraper. Ich liebe es.
