### ISSUE TITLE
[REQUEST] Allow for "custom continued" download of all following seasons

### ISSUE THREAD

**Issue by TrackLab** [wolfswolke/aniworld_scraper#68]
**Please describe what you want to be added/changed:**

Currently, you can either set Season to 0 to download the entire Series, or a single, custom season. 
Once my tool finished the job, I move the content to a different location. But some of the series are not finished yet, cause they have a huge amount of seasons.
I could download each next Season 1 by 1, sure, but it would be great if I could set the Season to something like "11+", so it downloads Season 11 and every other season after that, as long as they are available.

I might look into it myself if I have the time, but I dont know the whole setup of the "get seasons to download" algorithm, so I wanted to open this feature request.

**Comment by wolfswolke** [comment]
@TrackLab already started working on it.
Sadly my Pycharm is making me mad right now with saying nothing exists and everything is wrong.
I'll make a WIP commit in in_dev and try to solve this in the next few days / on the weekend.

**Comment by wolfswolke** [comment]
@TrackLab can you test the in-dev branch?
I already tested it on my pc with no issues.

**Comment by TrackLab** [comment]
I would, if I know how to select a season and its following ones, whats the command/syntax to do so?

**Comment by wolfswolke** [comment]
You should be able to use them how they are listed in the readme and or the old way.
`python main.py --type anime --name naruto-shippuden --lang Ger-Sub --mode all --season_override 17+ --provider VOE`

**Comment by TrackLab** [comment]
I run it over the run.bat file, not manually with giving arguments. Passing in 17+ results in a invalid type, since int() cant take in that string.

**Comment by wolfswolke** [comment]
@TrackLab fixed. You can try the BAT again. Should work now

**Comment by TrackLab** [comment]
Alright, seemed to work fine, I was able to download a manual selected season and the subsequent others

**Comment by wolfswolke** [comment]
Merged to Main.
