### ISSUE TITLE
Captcha solver[REQUEST] 

### ISSUE THREAD

**Issue by lude98** [wolfswolke/aniworld_scraper#7]
**Please describe what you want to be added/changed:**
Captcha solver

**Possible Solutions if you have any:**
https://github.com/dessant/buster

**Comment by wolfswolke** [comment]
I will not inclue a captcha bypass by default.
1. It makes is slower.
2. This is already a gray area. Adding that could get this project and me in trouble.
If you still want to add it you can do that in the captcha.py
Create a new var for it and option.add_argument it.
I do not take any responsibilty for what you do with or in this project.
