### ISSUE TITLE
[BUG] program just doesn't run [Exception: argument of type 'int' is not iterable]

### ISSUE THREAD

**Issue by 6odeWarrior** [wolfswolke/aniworld_scraper#72]
**Describe the bug:**

$ python3 main.py --type anime --name The-Seven-Deadly-Sins --lang Deutsch --dl-mode All --season-override 0 --provider Vidoza
2024-11-17 18:44:57 - INFO - src.start_app - ------------- AnimeSerienScraper v02-06 started ------------ 
2024-11-17 18:44:57 - DEBUG - src.start_app - We have Read Permission 
2024-11-17 18:44:57 - DEBUG - src.start_app - We have Write Permission 
2024-11-17 18:44:57 - ERROR - __main__ - ---------- 
2024-11-17 18:44:57 - ERROR - __main__ - Exception: argument of type 'int' is not iterable 
2024-11-17 18:44:57 - ERROR - __main__ - ---------- 

**Steps to Reproduce the bug:**
Download the .zip code
Extract the .zip
Open the main folder in terminal
Create virtual environment
Activate virtual environment
Install requirements.txt
run any example like: 
python3 main.py --type anime --name The-Seven-Deadly-Sins --lang Deutsch --dl-mode All --season-override 0 --provider Vidoza

**Expected behavior:**
Should start to download videos (i guess)

**Screenshots:**

**Logs:**

Please set the Log level to DEBUG in src/custom_logging.py

logging.basicConfig(level=logging.INFO) -> logging.basicConfig(level=logging.DEBUG)

No logs produced.

**Additional Info:**
I am running Linux Mint 21 with python 3.10.12.

Sorry if this is something stupid but i have spend some time trying to get this running without success, so i thought it's maybe worth to report.

**Comment by wolfswolke** [comment]
@6odeWarrior fixed. Can you test if it also works for you?

**Comment by 6odeWarrior** [comment]
Nothing changed on my side. Was you able to reproduce my issue?

**Comment by wolfswolke** [comment]
Did you download the latest version?

**Comment by wolfswolke** [comment]
You should now have a STRING conversion in start_app.py -> LINE 68: `str_season_override = str(season_override)`

**Comment by 6odeWarrior** [comment]
Yes i did. To be sure, i will try again

**Comment by 6odeWarrior** [comment]
> You should now have a STRING conversion in start_app.py -> LINE 68: `str_season_override = str(season_override)`

Yes i have this version

**Comment by 6odeWarrior** [comment]
Sorry i had to restart my terminal. Now it starts
